
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r - import packages}
rm(list = ls())

library(rstudioapi)
library(deSolve)
library(rootSolve)
library(tidyverse)
library(sensobol)
library(data.table)
library(EnvStats)
library(nimble)

```

```{r - load required functions and set up global parameters}
# Load required functions
source("Functions/system_of_RVF_equations_DEN.R", chdir = TRUE)
source("Functions/development_rate.R", chdir = TRUE)
source("Functions/mortality_rate.R", chdir = TRUE)
source("Functions/oviposition_rate.R", chdir = TRUE)
source("Functions/Sharpe_DeMichele_parameters.R", chdir=TRUE)
source("Functions/ponds.R", chdir = TRUE) 
source("Functions/temperature.R",chdir = TRUE)
source("Functions/biting_rate.R", chdir = TRUE)

# Set up global parameters needed by the ODE system functions
# These will be exported to parallel workers
#Parameters
  
delta_t <<- 1 # In days, the time step
N_ponds <<- 1 # How many ponds in each cell - not ever changed N_ponds from 1
reduction_C <<- 0.5 # Based on Figure 8 in Reisen, W. K., Fang, Y., & Martinez, V. M. (2006). Effects of temperature on the transmission of west nile virus by Culex tarsalis (Diptera: Culicidae). Journal of medical entomology, 43(2), 309–17. Retrieved from http://www.ncbi.nlm.nih.gov/pubmed/16619616
reduction_A <<- 0.58 # Based on Figure 8 in Reisen, W. K., Fang, Y., & Martinez, V. M. (2006). Effects of temperature on the transmission of west nile virus by Culex tarsalis (Diptera: Culicidae). Journal of medical entomology, 43(2), 309–17. Retrieved from http://www.ncbi.nlm.nih.gov/pubmed/16619616
b_L1 <<- 1/(5*365) # birth rate for livestock
mu_L1 <<- 1/(5*365) # death rate for livestock
# q_divided <<- 1E11 # parameter for the impact of the livestock on vector fecundity and gonotrophic cycles
q_A <<- 0.007 # probability of transovarial transmission
epsilon_L1 <<- 2/7# input by Sophie 1/2 - should it be 2/7?
gamma_L1 <<- 1/30 # input by Sophie 1/3     - should it be 30?
t_dep <<- 0.229 # average time for egg deposition = 0.229 days in lab ref(8) GL2018 supp

# SET Pond and Temperature Conditions--------------------------------------------------    

C_S_p <<- (17500)#8000  # this represents the average size of the ponds during the entire year. E.g. a dam of 100 m size on average
alpha <- 0.4
# maximum amplitude
A_S_p <<- (1-alpha)*C_S_p  #initial cond 0.2% of the mean  #  S_p_0<-C_S_p-A_S_p   this represents the size of the ponds at time 0 and time T=365 days.

omega_S_p <<- 2*3.14/(365)
phi_S_p <<- acos(-1) #both acos(-1) = in phase, one = acos(1)
pond_cond <- "periodic"

# temperature
omega_T_a <<- omega_S_p
phi_T_a <<- acos(-1)
C_T_a <<- 21 # mean temperature during period 2pi/omega_t
A_T_a <<- 7 # maximum amplitude
# livestocktotal <- 500
# N_L1 <- livestocktotal

```

```{r - define model}
system_of_RVF_equations_density_periodic_Aedes <- function(t, State, Pars) {
  
  with(as.list(c(State, Pars)), { # Variables from State & Pars brought into function
    
    temperature_t <- temperature_periodic(t) # Converts temps to Kelvin for each day
    # temperature_t <- constanttemp + 273.15 # Converts temps to Kelvin for each day when there is constant temperature
    
    # Mortality rates of species & life stage are dependent on temperature:
    
    mu_A_Oi <- mortality(temperature_t)[6] # Mortality rate for immature Aedes eggs
    mu_A_Om <- mortality(temperature_t)[7] # Mortality rate for mature Aedes eggs
    mu_A_L <- mortality(temperature_t)[8] # Mortality rate for Aedes larvae
    mu_A_P <- mortality(temperature_t)[9] # Mortality rate for Aedes pupae
    mu_A_E <- mortality(temperature_t)[10] # Mortality rate for additional Aedes pupal pupal (delta in paper)
    mu_A <- mortality(temperature_t)[11]  # Mortality rate for Aedes adult
    
    
    # Aedes dev rates (egg, larva & pupa) more complicated
    # Number of hatching eggs at time t-k will be null if:
    # k is less than the minimum desiccation period
    # Eggs were submerged before achieving min desiccation period
    
    Td <- 6 # 6 Minimum desiccation period in days

    delta_sp <- 0.197 #0.197 # proportion of spontaneous hatching without flooding
    
    
    # 1/rate = actual time for eggs to hatch, the bigger of:
    theta_A_O_inv <- pmax(Td, 1/Schoolfield(temperature_t, Aedes_Embryogenesis)) # eq. 15 GL2018 supplementary
    
    # Aedes developmental rates (egg, larva & pupa) dependent on temperature:
    
    theta_A_O <- 1/theta_A_O_inv
    theta_A_L <- Schoolfield(temperature_t, Aedes_Larval_development)
    theta_A_P <- Schoolfield(temperature_t, Aedes_Pupal_development)
    
    # Aedes developmental rates (adults) with infinite blood meal availability:
    
    theta_A_A1_no_lim <- 0.0173*(temperature_t - 273.16 - 9.60) # eq. 20 A1 GL2018 supplementary - from Fischer no matter Kelvin of celsius as we consider differences
    theta_A_A2_no_lim <- theta_A_A1_no_lim/reduction_A
    
    a_Culex <- biting_rate(temperature_t)[[1]]
    a_Aedes <- biting_rate(temperature_t)[[2]]
    
    epsilon_C <- EIP(temperature_t)[[1]] # Culex extrinsic incubation period
    epsilon_A <- EIP(temperature_t)[[2]] # Aedes extrinsic incubation period
    
    ov_A <- oviposition_rate__periodic_Aedes(t, Pars)[[1]] # Oviposition rate Aedes
    b_A <- oviposition_rate__periodic_Aedes(t, Pars)[[2]] # Eggs per batch Aedes
    K_A <- oviposition_rate__periodic_Aedes(t, Pars)[[3]] # Carrying capacity eggs in pond
    tau_A_O2 <- oviposition_rate__periodic_Aedes(t, Pars)[[4]] # Hatching rate Aedes
    
    # Total livestock   
    N_L1 <- livestocktotal
    
    # Total Aedes = only adults female A1 and A2 are biting
    N_Aedes <- (A1_a + A2_a)
    
    # If sum of eggs is less than zero, automatically set it to zero
    # Then, if sum of eggs exceeds carrying capacity, set to carrying capacity:
    Egg_Aedes <- min(max(O_a1 + O_a2, 0), K_A)
    
    # Vector to host ratio for Aedes:    
    m_A_L1 <- prop_find*(N_Aedes/N_L1)
    
    # These are the absolute developmental rates for adults: Take into account the vector to host ratio
    theta_A_A1 <- theta_A_A1_no_lim/(1 + (m_A_L1)/q_divided)
    theta_A_A2 <- theta_A_A2_no_lim/(1 + (m_A_L1)/q_divided)
    
    phi_L1_C <- 1 # proportion of meal, if multiple host need to use Sota model
    a_L1_C <- a_Culex*phi_L1_C # biting rate since phi = 1
    a_L1_C_dens <- a_L1_C/(1 + (m_A_L1)/q_divided)
    
    phi_L1_A <- 1 # proportion of meal, if multiple host need to use Sota model                             
    a_L1_A <- a_Aedes*phi_L1_A # biting rate since phi = 1                   
    a_L1_A_dens <- a_L1_A/(1 + (m_A_L1)/q_divided)                
    
    # Eggs laid per batch for Aedes   
    b_A_dens <- b_A/(1 + (m_A_L1)/q_divided)
    
    # DIFFERENTIAL EQUATIONS ---------------------------------------------------
    
    # Number entering compartment per day = positive
    # Number exiting compartment per day = negative
    
    # Immature eggs:
    dO_a1 <- b_A_dens*(1 - Egg_Aedes/K_A)*ov_A*(F_a) - mu_A_Oi*O_a1 - theta_A_O*O_a1
    # Mature eggs:
    dO_a2 <- (1 - delta_sp)*theta_A_O*O_a1 - mu_A_Om*O_a2 - tau_A_O2*O_a2
    # Larvae:
    dL_a <- tau_A_O2*O_a2 + theta_A_O*O_a1*delta_sp - mu_A_L*L_a - theta_A_L*L_a
    # Pupae:
    dP_a <- theta_A_L*L_a - mu_A_P*P_a - theta_A_P*P_a
    # Nulliparous adults:
    dA1_a <- theta_A_P*(mu_A_E/2)*P_a - mu_A*A1_a - theta_A_A1*A1_a
    # Flyers:
    dF_a <- theta_A_A1*A1_a + theta_A_A2*A2_a - ov_A*F_a - mu_A*F_a
    # Parous adults:
    dA2_a <- ov_A*F_a - mu_A*A2_a - theta_A_A2*A2_a  
    
    return(list(c(dO_a1,
                  dO_a2, dL_a,
                  dP_a, dA1_a,
                  dF_a, dA2_a)))
  }
  
  )
  
}
```

```{r - settings}
N <- 2000
day_length <<-365 * 11  #100
cellarea <<- 1 
prop_find <<- 0.1 # start mid = 10%, low = 0.01, high = 0.5

varying_params <- c("lambda_A", "rho_max_A", "A_A", "kappa_A","q_divided","livestocktotal")
fixed_params <- c(q_A, 
                  b_L1, 
                  mu_L1, 
                  epsilon_L1, 
                  gamma_L1, 
                  # q_divided, 
                  # as.numeric(N_L1), 
                  prop_find
                  # livestocktotal
                  )

times <- seq(0, day_length, by = delta_t)
timeOutput <- c(365*9,3316,3344,3375,3405,3436,3466,3497,3528,3558,3589,3619,3650,3681,3709,3740,3770,3801,3831,3862,3893,3923,3954,3984,4015)
```

```{r - construct sample matrix }

mat <- sobol_matrices(N = N, params = varying_params,order = "third")

mat[, "lambda_A"] <- qnorm(mat[, "lambda_A"], mean = 55, sd = 2.80)
mat[, "rho_max_A"] <- qunif(mat[, "rho_max_A"], min = 12000, max = 1000000)
mat[, "A_A"] <- qgamma(mat[, "A_A"], shape = 2.5 , scale = 10000)
mat[, "kappa_A"] <- qunif(mat[, "kappa_A"],min = 0.001, max = 0.999)
mat[, "q_divided"] <- qunif(mat[, "q_divided"], min = 1, max = 1E7)
mat[, "livestocktotal"] <- qunif(mat[, "livestocktotal"], min= 1, max = 1000)
```

```{r - run the model}

state_A <- c(O_a1 = 100,O_a2 = 0, L_a = 0, P_a = 0, A1_a = 0, F_a = 0, A2_a = 0)

time_taken <- system.time({
  
  y <- vector("list", nrow(mat))
  for (i in 1:nrow(mat)) {
    # Combine varying + fixed parameters
    param_run <- c(mat[i, ], fixed_params)
    
    y[[i]] <- sobol_ode(
      d = param_run,
      times = times,
      timeOutput = timeOutput,
      state = c(state_A),
      func = system_of_RVF_equations_density_periodic_Aedes
    )
    
    # Print progress every 1000 iterations (you can adjust this number)
    if (i %% 10000 == 0) {
      message("Completed ", i, " of ", nrow(mat), " simulations...")
    }
  }
})

print(paste("Time taken for running simulations and obtaining Sobol indices:", 
            time_taken["elapsed"], "seconds"))
```

```{r - convert to data frame}
# --------------------------
# 5. Convert to data frame
# --------------------------
y <- lapply(y, unlist)                    # flatten lists
Y <- as.data.frame(do.call(rbind, y))    # combine rows
Y_all <- as.data.frame(do.call(rbind, y))    # combine rows
# Assign run numbers and reshape to wide
n_times <- length(timeOutput)
n_runs <- nrow(mat)

Y$run <- rep(1:n_runs, each = n_times)
Y$time <- rep(timeOutput, times = n_runs)

Y <- Y %>%
  mutate(Adult_a = A1_a + F_a + A2_a)

# (Optional) Keep only run, time, and Adult_c
Y <- Y %>%
  select(run, time, Adult_a)

# Pivot wider (if you want one column per time)
Y_wide <- Y %>%
  pivot_wider(
    names_from = time,
    values_from = Adult_a,
    names_prefix = "Adult_a_"
  ) %>%
  mutate(across(starts_with("Adult_a_"), as.numeric))

```

```{r - compute sobol indices for all outputs}
# --------------------------
# 6. Compute Sobol indices for all outputs
# --------------------------
# compute Sobol indices only for combined adult counts at the two time points
# Automatically detect all Adult_c_* columns
outputs <- grep("^Adult_a_\\d+", names(Y_wide), value = TRUE)

sobol_list <- map(outputs, function(out) {
  res <- sobol_indices(Y = Y_wide[[out]], params = varying_params, N = N)
  tibble(
    output = out,
    parameter = res$results$parameters,
    index_type = res$results$sensitivity,
    value = res$results$original
  )
})

sobol_df <- bind_rows(sobol_list)

sobol_df <- sobol_df %>%
  mutate(
    time = str_extract(output, "\\d+"),         # extract numbers from column name
    variable = "Adults",                        # only one output type now
    index_type = ifelse(index_type == "Si", "First-order", "Total-order")
  )

```

```{r - plot for individual time points}
# --------------------------
# 7. Plot Sobol indices
# --------------------------
sobolPlot <- ggplot(sobol_df, aes(x = parameter, y = value, fill = index_type)) +
  geom_col(position = "dodge") +
  facet_grid(variable ~ time) +
  coord_flip() +
  labs(
    title = "Sobol Sensitivity Indices for Culex",
    x = "Parameter",
    y = "Sobol Index Value",
    fill = "Index Type"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "bottom",
    panel.grid.major.y = element_blank()
  )
sobolPlot
```

```{r - time plot with weather and mosquitoes}
library(patchwork)
library(ggtext)   # install.packages("ggtext")

# Time sequence
times <- seq(365*9, 365*11, by = 0.1)

times_reset <- seq(0, 365*2, by = 0.1)

# Shift so first element is 0
timeOutputShifted <- timeOutput - timeOutput[1]

timeOutputShifted

sobol_df$time <- as.numeric(sobol_df$time)
# Shift the time column so first entry becomes 0
sobol_df$time_shifted <- sobol_df$time - min(sobol_df$time)

sobol_df

# Temperature and water data
df_temps <- data.frame(time = times_reset, temperature = temperature_periodic(times_reset))
df_water <- data.frame(time = times_reset, water = S_p_periodic(times_reset))


#Ensure consistent types
sobol_df <- sobol_df %>% mutate(time = as.numeric(as.character(time_shifted)))
df_temps <- df_temps %>% mutate(time = as.numeric(as.character(time)))
df_water <- df_water %>% mutate(time = as.numeric(as.character(time)))


# Define a shared range before plotting
xlims <- range(c(sobol_df$time_shifted, df_temps$time, df_water$time), na.rm = TRUE)
# Define a labeller function
param_labels <- c(
  "A_A"           = "A<sub>A</sub>",           # subscript
  "kappa_A"       = "κ<sup><i>Aedes<i></sup>",      # superscript
  "lambda_A"      = "b<sub>A</sub>",          # subscript
  "rho_max_A"     = "ρ<sub>A</sub>",          # subscript
  "q_divided"     = "q",
  "livestocktotal"= "livestock <br> total"
)

p_sobol <- ggplot(sobol_df, aes(x = time, y = value, color = index_type, group = index_type)) +
  geom_line() +
  geom_point(size = 0.5)+
  facet_grid(parameter ~ variable, labeller = labeller(parameter = param_labels)) +
  scale_x_continuous(limits = xlims) +
  labs(x = expression(italic(t ) (days)), y = "Sobol Sensitivity Index", color = "Index Type") +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "top",
    strip.text.y = element_markdown()   # <-- this renders <sub>/<sup>
  )

p_temp <- ggplot(df_temps, aes(x = time, y = temperature)) +
  geom_line(color = "blue") +
  scale_x_continuous(limits = xlims) +   # same limits
  labs(x = NULL, y = "Mean Temperature \n (Kelvins)") +
  theme_minimal()

p_water <- ggplot(df_water, aes(x = time, y = water)) +
  geom_line(color = "darkgreen") +
  scale_x_continuous(limits = xlims) +   # same limits
  labs(x = NULL, y = "Mean Surface Area \n of Water Bodies (m^2)") +
  theme_minimal()
# 
# combined <- (p_sobol / p_temp / p_water) +
#   plot_layout(heights = c(5, 1, 1), guides = "collect") &
#   theme(legend.position = "top")

df_mosquito <- as.data.frame(do.call(rbind, y))    # combine rows

df_mosquito <- df_mosquito %>%
  mutate(simulation = rep(1:(n() / 25), each = 25))

df_mosquito_long <- df_mosquito %>%
  pivot_longer(
    cols = c(O_a1, O_a2, L_a, P_a, A1_a, F_a, A2_a),
    names_to = "stage",
    values_to = "count"
  )

df_mosquito_long <- df_mosquito_long %>%
  mutate(stage = factor(stage, levels = c("O_a1", "O_a2", "L_a", "P_a", "A1_a", "F_a", "A2_a")))

df_mosquito_summary <- df_mosquito_long %>%
  group_by(time, stage) %>%
  summarize(count = mean(count), .groups = "drop")

df_mosquito_summary$time_shifted <- df_mosquito_summary$time - min(df_mosquito_summary$time)

p_mosquito <- ggplot(df_mosquito_summary, aes(x = time_shifted, y = count, color = stage)) +
  geom_line() +
  geom_point(size=0.5)+
  labs(x = expression(italic(t) (days)), y = "Mosquito population") +
  scale_x_continuous(limits = xlims) +
  theme_minimal()+
  theme(
    legend.position = c(0.2, 0.98),   # (x, y) in relative plot coordinates (1 = right/top)
    legend.justification = c("right", "top"),  # anchor legend’s top-right corner
    legend.background = element_rect(fill = alpha("white", 0.6), color = "grey80"), # optional background box
    legend.title = element_text(size = 8),
    legend.text = element_text(size = 7),
    legend.key.size = unit(0.6, "lines") 
  )

xlims <- range(c(sobol_df$time, df_temps$time, df_water$time, df_mosquito_summary$time), na.rm = TRUE)

combined <- (p_sobol | p_temp / p_water / p_mosquito) +
  plot_layout(heights = c(6, 1, 1,1)) +
  theme(axis.title = element_text(size = 10),    # Axis labels
        axis.text = element_text(size = 8),      # Tick labels
        strip.text = element_text(size = 8),     # Facet titles
        plot.title = element_text(size = 12)     # Main title) 
        )
```

```{r}
save.image("Aedes_insync.RData")
ggsave(plot = combined, file = paste0("indices_aedes_insync.png"),
       width = 6, height = 4, device = png, scale=1.5)
```

